### Load in NumPy Library (remenber load in numpy first)

In [1]:
import numpy as np

### The Basics

In [12]:
a = np.array([1, 2, 3], dtype = 'int64')
print(a)

[1 2 3]


In [5]:
# get dimention
a.ndim

1

In [16]:
b = np.array([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
print(b)

[[1. 2. 3.]
 [4. 5. 6.]]


In [8]:
b.ndim

2

In [9]:
# get shape
a.shape

(3,)

In [10]:
b.shape

(2, 3)

In [11]:
#get type
a.dtype

dtype('int64')

In [17]:
# get size 
a.itemsize
b.itemsize

8

In [18]:
# get total size 
a.nbytes
b.nbytes

48

### Accessing/changeng specific elements, rows, columns, ect.

In [19]:
c = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
print(c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [22]:
# get a specific element [row, column]
c[1, 5]

13

In [23]:
# get a specific row
c[0, :]

array([1, 2, 3, 4, 5, 6, 7])

### Initialize different types of array

In [28]:
# ALL 0s matrixs
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [31]:
np.ones((2,3,4), dtype = 'int32')

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int32)

In [32]:
# type in all numbers 
np.full((2, 2), 88)

array([[88, 88],
       [88, 88]])

In [34]:
np.full_like(b, 4)

array([[4., 4., 4.],
       [4., 4., 4.]])

In [36]:
# random decimal number 
np.random.random_sample(a.shape)

array([0.41224693, 0.98752502, 0.68914247])

In [40]:
# random integer values
np.random.randint(-4, 8, size = (3, 3))

array([[ 6,  7,  6],
       [ 5, -3,  7],
       [ 1,  6, -1]])

In [41]:
# square matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [45]:
arr = np.array([[1, 2, 3]])
r1 = np.repeat(arr, 3, axis = 0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
